#!/bin/bash

# Applies one of four display modes (the Win+P equivalent). Called with a mode
# argument by the "Project" submenu in ~/.config/omarchy/extensions/omarchy-menu.jsonc;
# SUPER+ALT+P opens that menu.
#
# Modes are made to stick through Omarchy's toggle-flag directory
# (~/.local/state/omarchy/toggles/hypr/), every *.lua of which Hyprland
# re-sources on each reload. "extend/duplicate/external" ride Omarchy's own
# helpers; "laptop" and the extend layout need flags of our own since there is
# no stock helper for disabling the external or pinning monitor positions.
#
# Usage:
#   projection-menu.sh extend [right|left|up|down]
#   projection-menu.sh duplicate
#   projection-menu.sh external
#   projection-menu.sh laptop

set -euo pipefail

MODE="${1:-}"
DIR="${2:-}"

STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
TOGGLES_DIR="$STATE_HOME/omarchy/toggles/hypr"
MIRROR_FLAG="$TOGGLES_DIR/internal-monitor-mirror.lua"
INTERNAL_DISABLE_FLAG="$TOGGLES_DIR/internal-monitor-disable.lua"
EXTERNAL_DISABLE_FLAG="$TOGGLES_DIR/projection-external-disable.lua"
LAYOUT_FLAG="$TOGGLES_DIR/projection-layout.lua"
LAYOUT_MARK="$STATE_HOME/omarchy/projection-layout"

INTERNAL="$(omarchy-hyprland-monitor-laptop)"

mapfile -t EXTERNALS < <(
  hyprctl monitors all -j | jq -r '.[] | select(.name | test("^(eDP|LVDS|DSI)-") | not) | .name'
)

notify() { omarchy-notification-send -g 󰍹 "Display" "$1"; }

# A monitor name is written into generated Lua below, so only a plain connector
# name may pass; a hostile output name could execute otherwise.
safe_name() { [[ $1 =~ ^[A-Za-z0-9._-]+$ ]]; }

clear_external_disable_flag() { rm -f "$EXTERNAL_DISABLE_FLAG"; }
clear_layout_flag() { rm -f "$LAYOUT_FLAG" "$LAYOUT_MARK"; }

write_external_disable_flag() {
  local m
  : >"$EXTERNAL_DISABLE_FLAG"
  for m in "${EXTERNALS[@]}"; do
    safe_name "$m" || continue
    printf 'hl.monitor({ output = "%s", disabled = true })\n' "$m" >>"$EXTERNAL_DISABLE_FLAG"
  done
}

enable_externals_now() {
  local m
  for m in "${EXTERNALS[@]}"; do
    safe_name "$m" || continue
    hyprctl keyword monitor "$m,preferred,auto,auto" >/dev/null
  done
}

mode_dimensions() {
  hyprctl monitors all -j | jq -r --arg n "$1" '.[] | select(.name == $n) | "\(.width) \(.height)"'
}

# Pins the internal + first external at fixed positions for the chosen
# direction. The flag is Lua: it reads Omarchy's shared omarchy_monitor_scale
# at reload time and derives both the scale and the (logical-pixel) offset from
# it, so changing scale in the Display panel never leaves this stale.
write_layout_flag() {
  local dir="$1" external iw ih ew eh ipos epos
  external="${EXTERNALS[0]:-}"

  if [[ -z $INTERNAL || -z $external ]] || ! safe_name "$INTERNAL" || ! safe_name "$external"; then
    clear_layout_flag
    return
  fi

  read -r iw ih < <(mode_dimensions "$INTERNAL")
  read -r ew eh < <(mode_dimensions "$external")
  if ! [[ $iw =~ ^[0-9]+$ && $ih =~ ^[0-9]+$ && $ew =~ ^[0-9]+$ && $eh =~ ^[0-9]+$ ]]; then
    clear_layout_flag
    return
  fi

  case "$dir" in
  right) ipos='"0x0"'          epos="L($iw) .. \"x0\"" ;;
  left)  epos='"0x0"'          ipos="L($ew) .. \"x0\"" ;;
  up)    epos='"0x0"'          ipos="\"0x\" .. L($eh)" ;;
  down)  ipos='"0x0"'          epos="\"0x\" .. L($ih)" ;;
  *)
    clear_layout_flag
    return
    ;;
  esac

  cat >"$LAYOUT_FLAG" <<EOF
-- Generated by ~/.config/hypr/scripts/projection-menu.sh — extend layout "$dir".
-- Re-pick a layout in the Project menu (SUPER+ALT+P) to change it.
local scale = 1
do
  local f = io.open((os.getenv("HOME") or "") .. "/.config/hypr/monitors.lua", "r")
  if f then
    for line in f:lines() do
      local v = line:match("^local omarchy_monitor_scale = ([%d%.]+)")
      if v then scale = tonumber(v) or 1 end
    end
    f:close()
  end
end
local function L(px) return math.floor(px / scale + 0.5) end
hl.monitor({ output = "$INTERNAL", mode = "preferred", position = $ipos, scale = scale })
hl.monitor({ output = "$external", mode = "preferred", position = $epos, scale = scale })
EOF

  mkdir -p "$(dirname "$LAYOUT_MARK")"
  printf '%s\n' "$dir" >"$LAYOUT_MARK"
}

if [[ $MODE != laptop && ${#EXTERNALS[@]} -eq 0 ]]; then
  notify "No external display connected"
  exit 0
fi

case "$MODE" in
extend)
  clear_external_disable_flag
  omarchy-hyprland-monitor-internal-mirror off || true
  omarchy-hyprland-monitor-internal on || true
  if [[ -n $DIR ]]; then
    write_layout_flag "$DIR"
  else
    clear_layout_flag
  fi
  hyprctl reload >/dev/null
  if [[ -n $DIR ]]; then
    notify "Extending — external ${DIR}"
  else
    notify "Extending across all displays"
  fi
  ;;
duplicate)
  clear_external_disable_flag
  clear_layout_flag
  omarchy-hyprland-monitor-internal-mirror on || true
  notify "Duplicating the laptop screen"
  ;;
external)
  clear_external_disable_flag
  clear_layout_flag
  omarchy-hyprland-monitor-internal-mirror off || true
  # The internal-off helper refuses unless an external is already live.
  enable_externals_now
  omarchy-hyprland-monitor-internal off || true
  notify "External screen only"
  ;;
laptop)
  clear_layout_flag
  omarchy-hyprland-monitor-internal-mirror off || true
  omarchy-hyprland-monitor-internal on || true
  write_external_disable_flag
  hyprctl reload >/dev/null
  notify "Laptop screen only"
  ;;
*)
  echo "Usage: $(basename "$0") <extend [right|left|up|down]|duplicate|external|laptop>" >&2
  exit 2
  ;;
esac
