# Extra autostart processes
# exec-once = uwsm app -- my-service
exec-once = ~/.config/hypr/scripts/monitors.sh
exec-once = exec-start firefox
exec-once = hypridle 
exec-once = ~/.config/hypr/scripts/keep_screen_alive.sh
exec-once = ~/.config/hypr/scripts/toggle.sh
