# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
# bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER SHIFT, B, Browser (private), exec, $browser --private
bindd = SUPER, S, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER, C, Editor, exec, code 
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, M, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT, N, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm-app -- obsidian"
bindd = SUPER SHIFT,P, hdmi connected, exec, bash ~/.config/hypr/scripts/monitors.sh   
bindd = SUPER SHIFT, slash, Passwords, exec, uwsm app -- 1password

bindd = SUPER SHIFT, S, Toggle scratchpad, togglespecialworkspace, scratchpad

bindd = SUPER SHIFT ALT, C, Calendar, exec, omarchy-launch-webapp "https://app.hey.com/calendar/weeks/"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"
bindd = CTRL, 1, Switch to workspace 1, workspace, 1
bindd = CTRL, 2, Switch to workspace 2, workspace, 2
bindd = CTRL, 3, Switch to workspace 3, workspace, 3
bindd = CTRL, 4, Switch to workspace 4, workspace, 4
bindd = CTRL, 5, Switch to workspace 5, workspace, 5
bindd = ALT SHIFT, 1, Switch to workspace 6, workspace, 6
bindd = ALT SHIFT, 2, Switch to workspace 7, workspace, 7
bindd = ALT SHIFT, 3, Switch to workspace 8, workspace, 8
bindd = ALT SHIFT, 4, Switch to workspace 9, workspace, 9
bindd = ALT SHIFT, 5, Switch to workspace 10, workspace, 10

# Change windows from workspace
bindd = ALT, 1,move to workspace 1,  movetoworkspace, 1
bindd = ALT, 2,move to workspace 2,  movetoworkspace, 2
bindd = ALT, 3,move to workspace 3,  movetoworkspace, 3
bindd = ALT, 4,move to workspace 4,  movetoworkspace, 4
bindd = ALT, 5,move to workspace 5,  movetoworkspace, 5
bindd = ALT, 6,move to workspace 6,  movetoworkspace, 6
bindd = ALT, 7,move to workspace 7,  movetoworkspace, 7
bindd = ALT, 8,move to workspace 8,  movetoworkspace, 8
bindd = ALT, 9,move to workspace 9,  movetoworkspace, 9
bindd = ALT, 0,move to workspace 10, movetoworkspace, 10
bindd = SUPER SHIFT, J, $d toggle split, layoutmsg, togglesplit
#SCREENSHOT
bindd = SUPER SHIFT ALT, S, Screenshot of region, exec, omarchy-cmd-screenshot
# Color picker
bindd = ALT, C, Color picker, exec, pkill hyprpicker || hyprpicker -a

# Screen recordings
bindd = ALT, PRINT, Screen record a region, exec, omarchy-cmd-screenrecord region
bindd = ALT SHIFT, PRINT, Screen record a region with audio, exec, omarchy-cmd-screenrecord region audio
bindd = CTRL ALT, PRINT, Screen record display, exec, omarchy-cmd-screenrecord output
bindd = CTRL ALT SHIFT, PRINT, Screen record display with audio, exec, omarchy-cmd-screenrecord output audio

# Config laptop keys 
bindel =SUPER ,F5, exec, brightnessctl s 5%+ 
bindel = SUPER SHIFT,F4, exec, brightnessctl s 5%-
bind = SUPER SHIFT, F3, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = SUPER SHIFT, F2, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = , F1, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
