sub-font="Futura ND"
# sub-color="#D78B2E"
sub-color="#fff"
sub-scale=0.5
no-osd-bar
osd-font= "Helvetica"
osd-font-size= 9 
script-opts=osc-scalewindowed=0.5,osc-scalefullscreen=0.5
target-colorspace-hint=no
